# -*- coding: utf-8 -*-
"""llm-hallucination-african-education

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l0UI_NfotmmK8mP65NvKFYm8_c8LX8sO
"""

!pip install transformers torch shap matplotlib pandas seaborn -q

# pandas handles our dataset as a structured table (like Excel in Python)
import pandas as pd

# numpy handles numerical operations and array math
import numpy as np

# matplotlib.pyplot is our main charting library
import matplotlib.pyplot as plt

# seaborn builds on matplotlib — better heatmaps and statistical plots
import seaborn as sns

# pipeline is a high-level HuggingFace API — loads model + tokenizer together
# AutoTokenizer converts text into numbers the model understands
# AutoModelForCausalLM loads a causal language model (predicts next token)
from transformers import pipeline, AutoTokenizer, AutoModelForCausalLM

# torch is PyTorch — the framework powering our model computations
import torch

# warnings: we suppress non-critical warnings to keep output clean
import warnings
warnings.filterwarnings('ignore')

# io allows us to read a string as if it were a file (for our inline CSV)
import io

# json lets us save our summary results as a structured JSON file
import json

# Confirm everything loaded correctly
print("All imports successful")

# We define our 100 questions directly as a multi-line string
# This avoids needing to upload a separate file to Colab
# The format is CSV: two columns — question and category
csv_data = """question,category
What is photosynthesis?,global
What is Newton's First Law of Motion?,global
What is the capital of France?,global
What is the speed of light?,global
Who wrote Romeo and Juliet?,global
What is the Pythagorean theorem?,global
What is osmosis?,global
What is the chemical formula for water?,global
Who invented the telephone?,global
What is the theory of evolution?,global
What is the French Revolution?,global
What is DNA?,global
What is gravity?,global
Who was Albert Einstein?,global
What is the periodic table?,global
What is democracy?,global
What is the Industrial Revolution?,global
What is photovoltaic energy?,global
What is the United Nations?,global
What is climate change?,global
What is artificial intelligence?,global
What is the internet?,global
What is plate tectonics?,global
What is the Big Bang theory?,global
What is capitalism?,global
What is the Roman Empire?,global
What is the Cold War?,global
What is the Renaissance?,global
What is Newtonian mechanics?,global
What is the World Health Organization?,global
What is the human immune system?,global
What is blockchain?,global
What is quantum mechanics?,global
What is the law of supply and demand?,global
What is a chromosome?,global
What is the Magna Carta?,global
What is World War II?,global
What is photosynthesis in plants?,global
What is the solar system?,global
What is the mitochondria?,global
What is a black hole?,global
What is the greenhouse effect?,global
What is the United States Constitution?,global
What is nuclear fission?,global
What is the theory of relativity?,global
What is machine learning?,global
What is the water cycle?,global
What is the food chain?,global
What is the Bill of Rights?,global
What is algebra?,global
Who was Nigeria's first president?,african
What is ECOWAS?,african
What year did Ghana gain independence?,african
What is the River Niger?,african
Who was Kwame Nkrumah?,african
What is the African Union?,african
What happened during the Biafran War?,african
Who is Wole Soyinka?,african
What is the significance of Gorée Island?,african
What was the Berlin Conference of 1884?,african
Who was Patrice Lumumba?,african
What is the Great Rift Valley?,african
What is NEPAD?,african
Who was Nelson Mandela?,african
What is the Nile River?,african
What was apartheid?,african
Who was Haile Selassie?,african
What is the Lagos Plan of Action?,african
What is the significance of Timbuktu?,african
Who was Shaka Zulu?,african
What is the Sahel?,african
What was the Mau Mau uprising?,african
Who is Chinua Achebe?,african
What is the significance of the Ashanti Kingdom?,african
What is AFRICOM?,african
Who was Thomas Sankara?,african
What is the Horn of Africa?,african
What was the Scramble for Africa?,african
Who is Ngozi Okonjo-Iweala?,african
What is the significance of Great Zimbabwe?,african
What is the Niger Delta?,african
What was the Rwandan Genocide?,african
Who was Jomo Kenyatta?,african
What is the African Development Bank?,african
What is Ubuntu philosophy?,african
Who was Samora Machel?,african
What is the significance of the Benin Bronzes?,african
What was the Chimurenga War?,african
Who is Wangari Maathai?,african
What is the SADC?,african
What is the significance of Carthage?,african
Who was Amilcar Cabral?,african
What is the Maghreb?,african
What was the Zanzibar Revolution?,african
Who is Aliko Dangote?,african
What is the significance of the Kingdom of Mali?,african
What was the Defiance Campaign in South Africa?,african
Who was Obafemi Awolowo?,african
What is the East African Community?,african
What is the significance of Lake Victoria?,african"""

# io.StringIO converts our string into a file-like object
# pd.read_csv then reads it exactly like a real CSV file
df = pd.read_csv(io.StringIO(csv_data))

# Confirm the dataset loaded correctly
print(f"Dataset loaded: {len(df)} questions")

# value_counts() shows how many questions are in each category
print(df['category'].value_counts())

# We print this so we know the model is loading — it takes 1-2 minutes
print("Loading DistilGPT-2...")

# pipeline() is HuggingFace's simplified API for running models
# 'text-generation' tells it we want the model to generate text
# model='distilgpt2' loads a lightweight 82M parameter language model
# distilgpt2 is small enough to run on Colab's free CPU tier
# device=-1 means use CPU (change to 0 if you have a GPU available)
generator = pipeline(
    'text-generation',
    model='distilgpt2',
    device=-1
)

print("Model loaded successfully")

# This function takes a question and returns the model's generated answer
def generate_answer(question, max_new_tokens=80):
    # We format the question as a prompt the model can respond to
    # This "Question: ... Answer:" format guides the model's output
    prompt = f"Question: {question}\nAnswer:"

    try:
        # We pass the prompt to the generator
        # max_new_tokens=80 limits how long the answer can be
        # num_return_sequences=1 means we only want one answer
        # temperature=0.7 controls randomness (0=deterministic, 1=very random)
        # do_sample=True enables sampling (needed when temperature != 1)
        # pad_token_id=50256 is GPT-2's end-of-sequence token
        result = generator(
            prompt,
            max_new_tokens=max_new_tokens,
            num_return_sequences=1,
            temperature=0.7,
            do_sample=True,
            pad_token_id=50256
        )

        # result[0]['generated_text'] contains the full prompt + answer
        full_text = result[0]['generated_text']

        # We split on "Answer:" and take everything after it
        # strip() removes leading and trailing whitespace
        answer = full_text.split("Answer:")[-1].strip()
        return answer

    except Exception as e:
        # If anything goes wrong, we return the error message
        # This prevents the whole loop from crashing on one bad question
        return f"ERROR: {str(e)}"

print("Generating answers for all 100 questions...")
print("This will take about 5-10 minutes...\n")

# We create an empty list to collect all generated answers
answers = []

# df.iterrows() loops through every row in our dataframe
# i is the row index (0 to 99), row contains the question and category
for i, row in df.iterrows():
    # Generate the model's answer for this question
    answer = generate_answer(row['question'])

    # Add the answer to our list
    answers.append(answer)

    # Print progress every 10 questions so we know it's running
    if (i + 1) % 10 == 0:
        print(f"Progress: {i+1}/100 questions done")

# Add the answers as a new column in our dataframe
df['model_answer'] = answers

print("\nDone! Saving results...")

# Save to CSV so we don't lose the answers if Colab disconnects
df.to_csv('results_raw.csv', index=False)
print("Saved to results_raw.csv")

# This setting prevents pandas from cutting off long text in display
pd.set_option('display.max_colwidth', 200)

# We print global questions first so we can read and score them
print("=== GLOBAL QUESTIONS ===\n")

# Filter the dataframe to only global questions
global_df = df[df['category'] == 'global'].copy()

# Loop through each global question and print question + answer
for i, row in global_df.iterrows():
    print(f"Q{i+1}: {row['question']}")
    print(f"A: {row['model_answer']}")
    # Dashes visually separate each Q&A pair for easier reading
    print("-" * 60)

print("\n=== AFRICAN QUESTIONS ===\n")

# Filter to only African questions
african_df = df[df['category'] == 'african'].copy()

for i, row in african_df.iterrows():
    print(f"Q{i+1}: {row['question']}")
    print(f"A: {row['model_answer']}")
    print("-" * 60)

# After running this cell, read every answer carefully
# Then go to Cell 7 and fill in your manual scores
print("\nNow read all answers above and fill in your scores in Cell 7")

global_scores = [2,1,1,2,2,2,2,2,2,1,1,2,2,2,2,2,2,1,2,1,1,0,2,2,2,2,2,2,0,0,2,0,1,2,2,1,2,2,2,2,2,1,1,1,1,1,2,2,2,1]

african_scores = [2,2,2,2,2,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
# We separate the dataframe back into global and african
df_global = df[df['category'] == 'global'].copy()
df_african = df[df['category'] == 'african'].copy()

# Assign our manual scores as a new column in each sub-dataframe
df_global['hallucination_score'] = global_scores
df_african['hallucination_score'] = african_scores

# Merge both back into one complete scored dataframe
df_scored = pd.concat([df_global, df_african])

# Save the scored results to CSV
df_scored.to_csv('results_scored.csv', index=False)
print("Scores saved to results_scored.csv!")

# Show a breakdown of how many questions got each score per category
print("\nScore distribution:")
print(df_scored.groupby('category')['hallucination_score'].value_counts())

# This function calculates the hallucination rate for a list of scores
# "Hallucination" here means score >= 1 (partial or full error)
# We divide by total count and multiply by 100 to get a percentage
def hallucination_rate(scores):
    return round(sum(s >= 1 for s in scores) / len(scores) * 100, 1)

# This function calculates the SEVERE hallucination rate (score == 2 only)
# These are the cases where the model was completely wrong
def severe_rate(scores):
    return round(sum(s == 2 for s in scores) / len(scores) * 100, 1)

# Calculate all four key metrics
global_hall = hallucination_rate(global_scores)   # global any-error rate
african_hall = hallucination_rate(african_scores)  # african any-error rate
global_severe = severe_rate(global_scores)          # global severe rate
african_severe = severe_rate(african_scores)        # african severe rate

# Print a clean summary table
print("=" * 50)
print("HALLUCINATION ANALYSIS RESULTS")
print("=" * 50)
print(f"\nGlobal Questions:")
print(f"  Any error rate:    {global_hall}%")
print(f"  Severe error rate: {global_severe}%")
print(f"\nAfrican Questions:")
print(f"  Any error rate:    {african_hall}%")
print(f"  Severe error rate: {african_severe}%")

# The gap is the most important finding — this is your headline result
print(f"\nGap (African minus Global): {round(african_hall - global_hall, 1)} percentage points")
print("=" * 50)

# Create a figure with 2 side-by-side subplots
# figsize=(12, 5) sets the width and height in inches
fig, axes = plt.subplots(1, 2, figsize=(12, 5))

# Add a title that spans both subplots
fig.suptitle(
    'Hallucination Patterns in DistilGPT-2:\nGlobal vs African Educational Questions',
    fontsize=13,
    fontweight='bold'
)

# ── PLOT 1: Bar chart comparing hallucination rates ──────────────────────────

# Labels for the x-axis
categories = ['Global\nQuestions', 'African\nQuestions']

# The actual hallucination rate values we calculated in Cell 8
rates = [global_hall, african_hall]

# Blue for global, red for african — intuitive color contrast
colors = ['#2196F3', '#F44336']

# Draw the bars
bars = axes[0].bar(
    categories,
    rates,
    color=colors,
    width=0.5,         # bar width
    edgecolor='black', # black border around each bar
    linewidth=0.8
)

# Label the y-axis
axes[0].set_ylabel('Hallucination Rate (%)', fontsize=11)
axes[0].set_title('Overall Hallucination Rate by Category', fontsize=11)

# Set y-axis from 0 to 100 (percentage scale)
axes[0].set_ylim(0, 100)

# Add the percentage number on top of each bar
for bar, rate in zip(bars, rates):
    axes[0].text(
        bar.get_x() + bar.get_width() / 2,  # center of bar
        bar.get_height() + 1.5,              # just above bar
        f'{rate}%',
        ha='center',
        fontsize=12,
        fontweight='bold'
    )

# Reference line at 50% for visual context
axes[0].axhline(y=50, color='gray', linestyle='--', alpha=0.4, label='50% reference')

# ── PLOT 2: Score distribution grouped bar chart ─────────────────────────────

# Labels for the three score levels
score_labels = ['Correct (0)', 'Partial Error (1)', 'Hallucinated (2)']

# Count how many questions received each score in each category
global_counts = [global_scores.count(i) for i in range(3)]
african_counts = [african_scores.count(i) for i in range(3)]

# x positions for the three groups
x = np.arange(3)
width = 0.35  # width of each bar within a group

# Draw global bars slightly to the left of center
axes[1].bar(
    x - width / 2, global_counts, width,
    label='Global', color='#2196F3',
    edgecolor='black', linewidth=0.8
)

# Draw african bars slightly to the right of center
axes[1].bar(
    x + width / 2, african_counts, width,
    label='African', color='#F44336',
    edgecolor='black', linewidth=0.8
)

# Set x-axis tick labels to our score names
axes[1].set_xticks(x)
axes[1].set_xticklabels(score_labels, fontsize=9)
axes[1].set_ylabel('Number of Questions', fontsize=11)
axes[1].set_title('Score Distribution by Category', fontsize=11)

# Add a legend to distinguish global vs african bars
axes[1].legend()

# Adjust spacing between subplots
plt.tight_layout()

# Save figure to disk as a high-quality PNG
plt.savefig('hallucination_comparison.png', dpi=150, bbox_inches='tight')
plt.show()
print("Figure saved as hallucination_comparison.png")

# We reload the model separately here because we need access to
# the raw attention weights, which the pipeline() API hides from us
print("Loading model with attention outputs enabled...")

# AutoTokenizer converts text strings into token ID sequences
# A token is roughly a word or word-fragment the model understands
tokenizer = AutoTokenizer.from_pretrained('distilgpt2')

# AutoModelForCausalLM loads the actual transformer model
# output_attentions=True tells PyTorch to return attention matrices
# These matrices show which tokens the model "focuses on" at each layer
model = AutoModelForCausalLM.from_pretrained(
    'distilgpt2',
    output_attentions=True
)

# model.eval() sets the model to evaluation mode
# This disables dropout layers that are only used during training
model.eval()

def get_attention_for_question(question):
    # Format the question as a prompt (same format as generation)
    prompt = f"Question: {question}\nAnswer:"

    # tokenizer() converts our text into input_ids (integer token IDs)
    # return_tensors='pt' returns PyTorch tensors (needed by the model)
    inputs = tokenizer(prompt, return_tensors='pt')

    # torch.no_grad() disables gradient computation
    # We don't need gradients for inference — this saves memory and speed
    with torch.no_grad():
        outputs = model(**inputs)

    # outputs.attentions is a tuple of attention matrices — one per layer
    # We take the LAST layer [-1] as it captures the most abstract patterns
    # Shape: (batch_size, num_heads, seq_len, seq_len)
    attentions = outputs.attentions[-1]

    # We average across all attention heads (dim=0 after removing batch dim)
    # This gives us one attention matrix showing average focus patterns
    avg_attention = attentions[0].mean(dim=0)

    # Convert token IDs back to readable strings for axis labels
    tokens = tokenizer.convert_ids_to_tokens(inputs['input_ids'][0])

    return tokens, avg_attention

# We pick one representative question from each category
# These are good examples because they're similar in structure
# but one has rich training data (France) and one may not (Nigeria)
global_q = "What is the capital of France?"
african_q = "Who was Nigeria's first president?"

# Get attention matrices and tokens for both questions
tokens_g, attn_g = get_attention_for_question(global_q)
tokens_a, attn_a = get_attention_for_question(african_q)

# Create side-by-side heatmap figure
fig, axes = plt.subplots(1, 2, figsize=(14, 5))

# We only show the first 12 tokens to keep the heatmap readable
# min() handles cases where a question has fewer than 12 tokens
n = min(12, len(tokens_g))

# sns.heatmap draws the attention matrix as a color grid
# Each cell [i,j] shows how much token i attends to token j
# cmap='Blues' uses a blue color scale for the global question
sns.heatmap(
    attn_g[:n, :n].numpy(),       # convert PyTorch tensor to numpy array
    xticklabels=tokens_g[:n],      # token labels on x-axis (keys)
    yticklabels=tokens_g[:n],      # token labels on y-axis (queries)
    ax=axes[0],
    cmap='Blues',
    linewidths=0.3                 # thin grid lines between cells
)
axes[0].set_title(f'Attention: Global Q\n"{global_q}"', fontsize=9)
axes[0].tick_params(axis='x', rotation=45, labelsize=7)
axes[0].tick_params(axis='y', rotation=0, labelsize=7)

# Same process for the African question — red color scale for contrast
n = min(12, len(tokens_a))
sns.heatmap(
    attn_a[:n, :n].numpy(),
    xticklabels=tokens_a[:n],
    yticklabels=tokens_a[:n],
    ax=axes[1],
    cmap='Reds',
    linewidths=0.3
)
axes[1].set_title(f'Attention: African Q\n"{african_q}"', fontsize=9)
axes[1].tick_params(axis='x', rotation=45, labelsize=7)
axes[1].tick_params(axis='y', rotation=0, labelsize=7)

plt.suptitle(
    'Attention Pattern Comparison: Global vs African Questions',
    fontsize=11,
    fontweight='bold'
)
plt.tight_layout()
plt.savefig('attention_comparison.png', dpi=150, bbox_inches='tight')
plt.show()
print("Attention visualization saved as attention_comparison.png")

# Filter to only questions where the model made errors (score >= 1)
# This lets us study WHICH questions failed and look for patterns
df_errors = df_scored[df_scored['hallucination_score'] >= 1].copy()

# Further split into african and global errors separately
df_african_errors = df_errors[df_errors['category'] == 'african']
df_global_errors = df_errors[df_errors['category'] == 'global']

print("=" * 50)
print("FAILURE PATTERN ANALYSIS")
print("=" * 50)

# Print every African question that had an error
# This is where you look for patterns: history questions? People's names?
print(f"\nAfrican questions with errors ({len(df_african_errors)}):")
for _, row in df_african_errors.iterrows():
    # Give each error a human-readable label based on severity
    score_label = "PARTIAL" if row['hallucination_score'] == 1 else "HALLUCINATED"
    print(f"  [{score_label}] {row['question']}")

# Print every global question that had an error for comparison
print(f"\nGlobal questions with errors ({len(df_global_errors)}):")
for _, row in df_global_errors.iterrows():
    score_label = "PARTIAL" if row['hallucination_score'] == 1 else "HALLUCINATED"
    print(f"  [{score_label}] {row['question']}")

# Prompt yourself to write observations — these go in the README
print("\n--- WRITE YOUR OBSERVATIONS BELOW ---")
print("After reviewing the error lists above, note:")
print("1. Are African history or governance questions failing more than geography?")
print("2. Do errors about specific people (names) cluster together?")
print("3. Are the errors confident-sounding or vague and rambling?")
print("4. Is there a pattern in WHICH African questions the model got right?")

# Save the complete scored dataframe as our final results file
df_scored.to_csv('results_final.csv', index=False)

# Build a summary dictionary with all our key metrics
# This is useful for citing specific numbers in the README and CV
summary = {
    'model': 'distilgpt2',                          # which model we tested
    'total_questions': 100,                          # total dataset size
    'global_hallucination_rate': global_hall,        # % of global errors
    'african_hallucination_rate': african_hall,      # % of african errors
    'global_severe_rate': global_severe,             # % of global severe errors
    'african_severe_rate': african_severe,           # % of african severe errors
    'gap_percentage_points': round(african_hall - global_hall, 1)  # headline finding
}

# Save summary as JSON — a clean structured format easy to reference later
with open('summary_results.json', 'w') as f:
    json.dump(summary, f, indent=2)
# indent=2 makes the JSON file human-readable with 2-space indentation

# Confirm everything was saved
print("All files saved successfully:")
print("  results_final.csv        — full scored dataset")
print("  summary_results.json     — key metrics summary")
print("  hallucination_comparison.png  — bar charts")
print("  attention_comparison.png      — attention heatmaps")
print("\nYour experiment is complete. Push everything to GitHub.")